### ISSUE TITLE
Topluluk sayfasına pagination

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#100]

**Comment by sayginburak** [comment]
@enderahmetyurt ben bunu ve #90'ı yaptım 1 ay önce falan. bi de test yazip PR açayım dedim ama test yazmaya fırsat olmadı. testleri yazınca göndereceğim. :D

**Comment by enderahmetyurt** [comment]
@sayginburak aa süper. testleri yaz tabiki. testsiz PR olmaz :D

**Comment by enderahmetyurt** [comment]
nabtın @sayginburak :)
