### ISSUE TITLE
"Haftalık Bülten" güncelliği hakkında

### ISSUE THREAD

**Issue by enig** [rubytr/ruby-tr#101]
Ana sayfada "**Nasıl iletişim kurabilirim ?**" başlığı altında bulunan "**Haftalık Bülten**" içeriği güncel tutulmadığı için _üzeri çizgili biçimde görünmesi ve üzerine gelinde "Artık güncellenmiyor"_ yada daha uygun olabilecek bir ifade çıkması konusunda katkınızı bekliyorum.

> OYK2019 Ruby on Rails sınıfında topluluğa katkı amacıyla başlangıçtır.

**Comment by hasantezcan** [comment]
:+1: https://github.com/rubytr/ruby-tr/pull/102
