### ISSUE TITLE
Updating rubocop gem

### ISSUE THREAD

**Issue by sarslanoglu** [rubytr/ruby-tr#119]
Current rubocop version is 0.59.2
Latest current is 0.83.0

**Comment by krmbzds** [comment]
Dün akşam [rails_upgade](https://github.com/rubytr/ruby-tr/compare/rails_upgrade)  branch'inde 0.83.0 cop'larını çalıştırıp bazı güncellemeler yaptım. Vaktim olunca kalan sorunları da çözüp bütün gem'leri güncelleyip Rails upgrade'ine uygun hale getirmek istiyorum.

**Comment by enderahmetyurt** [comment]
PR'lari bekliyorum.

**Comment by sarslanoglu** [comment]
@krmbzds 0.84.0 cikti bu arada 11 saat once

**Comment by enderahmetyurt** [comment]
@krmbzds PR neden acmadin?

**Comment by krmbzds** [comment]
@enderahmetyurt Henüz bir değişiklik propose etmediğim için PR açmadım.

Geldiğim noktaya kadar olan kısımdan 3-4 PR çıkabilir (patlayan testler, deprecation'lar, humanize/captcha ile ilgili olan kısımların silinmesi vs). Vaktim olmadığı için yarım kaldı, hem yedeği olsun hem de merak eden baksın diye branch'e pushladım. Vaktim olunca devam edeceğim.
