### ISSUE TITLE
Setting up a CI for project

### ISSUE THREAD

**Issue by sarslanoglu** [rubytr/ruby-tr#120]
Benim bildigim circleci ve travis var. Bu konu basligini tartisma icin kullanabiliriz. Travis hem open-source olan projeler icin ucretsiz, hem de kullanmasi inanilmaz basit. Circleci ise biraz daha zor konfigurasyon anlaminda ama private projelerde de ucretsiz kullanilabiliyor. Sizin onerileriniz neler?
@rubytr/core

**Comment by hwpplayer1** [comment]
> Benim bildigim circleci ve travis var. Bu konu basligini tartisma icin kullanabiliriz. Travis hem open-source olan projeler icin ucretsiz, hem de kullanmasi inanilmaz basit. Circleci ise biraz daha zor konfigurasyon anlaminda ama private projelerde de ucretsiz kullanilabiliyor. Sizin onerileriniz neler?
> @rubytr/core

circleci tanıtımını izledim ben ona yönelmekten yanayım ama siz daha deneyimlisiniz sadece öneriyorum

**Comment by enderahmetyurt** [comment]
ekle gec abi ucretsizse. :)

**Comment by kadir96** [comment]
Aynen ucretsiz ve hangisi kolayina geliyorsa ekle gitsin :)
