### ISSUE TITLE
Proposal page

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#121]
Sadece tartisalim diye actim. Meetup ve lighting talk yapmak isteyenler icin buraya bir propasal sayfasimi acsak ornek olarak https://www.rug-b.de/topics/new

**Comment by krmbzds** [comment]
Doğrudan [on_ruby](https://github.com/phoet/on_ruby)'yi alıp niye kullanmıyoruz?

(Benim de aklıma bu geldi)

**Comment by enderahmetyurt** [comment]
ne icin on_ruby kullanacaginiz? butun site icin mi?

**Comment by krmbzds** [comment]
Evet, codebase güncel ve maintain ediliyor. Yeniden yapmak yerine komple buna geçebiliriz aslında. Maintenance da daha kolay olur bir kere geçtikten sonra (upstream'den güncellemeleri çekeriz).

Onun dışında alt gruplar için de desteği var. İleride Ruby İstanbul, Ruby Ankara, Ruby İzmir gibi usergroup'lar olursa extend etmesi de kolay olur.

**Comment by enderahmetyurt** [comment]
olabilir ama bu da guzel. kendimiz maintain ediyoruz. direk bize ait yerli milli :D
