### ISSUE TITLE
Issue ve PR şablonları - Default templates for issues and PR's

### ISSUE THREAD

**Issue by sarslanoglu** [rubytr/ruby-tr#126]
Bu issue altında tartışabiliriz. Proje için ufak bir issue ve pull request şablonu belirleyip bunları kullanabiliriz. Gerekirse türkçe olarakta ekleyebiliriz. Çok kasıntı ve projeye katkıyı baltalar diye de bilirsiniz. Kendi projemde kullanmaya başladığım template örnek olması adına:

### Related github issue for this PR

Resolves #001 

### Checklist

* [ ] I have performed a self-review of my own code
* [ ] I added comments, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation `README.md`
* [ ] I added tests that prove my fix is effective or that my feature works
* [ ] `bundle exec rake` passes locally
* [ ] `rubocop` gives no error locally
* [ ] My PR title includes "WIP" or is [draft PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) if work is in progress

### Description

#In comment (Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.
Guide questions:
  - What changed, and why?
  - What alternative solutions did you consider?
  - What are the tradeoffs for your solution?

Include anything else we should know about. )

### Type of change

#In comment (Please delete options that are not relevant.)

* Bug fix (non-breaking change which fixes an issue)
* New feature (non-breaking change which adds functionality)
* Breaking change (fix or feature that would cause existing functionality to not
work as expected)
* Documentation update

### Which tests are written for this PR? And what are the expected results for these tests?

#In comment (Please describe the tests that you ran to verify your changes.)

**Comment by MuhammetDilmac** [comment]
Eline sağlık @sarslanoglu türkçe olmasının kesinlikle gerektiğini düşünüyorum sonuçta Ruby Türkiye olarak geçiyoruz :)
