### ISSUE TITLE
Broken Subdomain: www

### ISSUE THREAD

**Issue by MuhammetDilmac** [rubytr/ruby-tr#132]
www subdomaini üzerinden siteye erişilemiyor. www ile başlayan tüm linkler bu yüzden kırık şuanda.

<img width="1533" alt="resim" src="https://user-images.githubusercontent.com/6417144/83447133-9c06f380-a458-11ea-8aab-1f89e7905b9c.png">

**Comment by enderahmetyurt** [comment]
sakin ol sampiyon :) nginx degil heroku'dan yapmak lazim 2.si www domaini yok sanirim. cok sallamiyoruz o yuzden bi suredir. istersen notion'a is ac abi. onur'daydi domain bi konus.

**Comment by MuhammetDilmac** [comment]
Eğer kullanmayacak isek sitenin içinde ki www'leri www'siz yapalım abi notion'a atıyorum :)

**Comment by enderahmetyurt** [comment]
rubyturkiye.org sitesinin icinde boyle linkler varsa abi issue acabilirsin ya da yapabilirsin.

**Comment by tayfunoziserikan** [comment]
Domain yönlendirme CNAME A kaydı gibi konular için Cloudflare kullanıyoruz. Buraya not olarak düşeyim. Fyi.

**Comment by MuhammetDilmac** [comment]
Evet abi onu gördüm kolaylıkla bu sorunu çözeriz oradan sanırım SSL kısmında sorun var www'nun domain olarak varda ssl handshake edemiyor. Çözüm için şu döküman yazılmış. https://community.cloudflare.com/t/community-tip-fixing-error-525-ssl-handshake-failed/44256 Cloudflare yetkisi kimdeyse artık ona assign edelim ellerinden öper 😄

**Comment by enderahmetyurt** [comment]
bu konu bende. yetki bekliyorum @tayfunoziserikan 'dan

**Comment by enderahmetyurt** [comment]
@tayfunoziserikan baktirdi app'de birseyler yapmak gerek sanirim. @MuhammetDilmac ilgilenmek ister misin?

**Comment by kadir96** [comment]
@enderahmetyurt cloudflare den direk **Page Rule** ile www yi non-www olarak yonlendirme yapsak app e mudahale etmeye gerek kalmadan halledebiliriz

**Comment by enderahmetyurt** [comment]
orada hesap vermedi tayfun bana. yani konuya ben bakamiyorum ne yaziki. @tayfunoziserikan erisimi var.

**Comment by MuhammetDilmac** [comment]
Sorunu anlayabilmek için sunucu tarafta ve cf'de kontrol etmek gerek. CF'de ssl ayarları nasıl vs bakmak gerek. Sunucu tarafa istekler ssl protokolünden mi gidiyor yoksa cf ye kadar mı ssl vs... İki tarafa da bakmam lazım app'lik bir şey olmaz burada

**Comment by kadir96** [comment]
Sorunun basic bir cozumu varken niye ugrasiyoruz ki :)

**Comment by enderahmetyurt** [comment]
nasil @kadir96

**Comment by kadir96** [comment]
> @enderahmetyurt cloudflare den direk **Page Rule** ile www yi non-www olarak yonlendirme yapsak app e mudahale etmeye gerek kalmadan halledebiliriz

@enderahmetyurt

**Comment by MuhammetDilmac** [comment]
Kadir www.rubyturkiye.org'a gelen istekleri cf'de direkt rubyturkiye.org'a yönlendirelim diyor

**Comment by enderahmetyurt** [comment]
abi cloudflare'a yetkim yok

**Comment by kadir96** [comment]
Nasil yapilacagini ss olarak buraya koyayim. Yetkisi olan yapsin nasi fikir?

**Comment by MuhammetDilmac** [comment]
@tayfunoziserikan abi redirection da parametre vermek lazım
https://www.rubyturkiye.org/* -> https://rubyturkiye.org/$1

**Comment by enderahmetyurt** [comment]
bu konu tamam sanirim

**Comment by MuhammetDilmac** [comment]
Şuan ki konfigürasyonda https://www.rubyturkiye.org/companies'e gidince https://rubyturkiye.org'a yönlendiriyor üstte ki yorumda yazdığım şekilde konfigürasyon girilirse https://www.rubyturkiye.org/companies'e gidilince https://rubyturkiye.org/companies'e yönlendirilecek daha hoş olur bence :)
