### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by MuhammetDilmac** [rubytr/ruby-tr#140]
Projede ki testler çok yetersiz bunu biran önce halletmemiz gerekli.

**Comment by sarslanoglu** [comment]
@MuhammetDilmac Capybara tarzi bir sey kurmak gerek, sen ne dersin? Su an ki testler sadece controller istek aliyor mu, 401 atiyor mu tarzinda? Bundan ziyade gercekten kullanici gibi sayfaya girip formu dolduran testler lazim bize. Bu issue'yu kapatmayip testlerle alakali tum PR'lari buraya refere edelim bir sure
