### ISSUE TITLE
[HATA] - Bazı kullanıcıların profillerinde bulunan twitter linkleri yanlış formatta

### ISSUE THREAD

**Issue by sarslanoglu** [rubytr/ruby-tr#146]
### Hatanın tarifi
Twitter linkleri için twitter_url helper kullanıyoruz ama kullanıcılardan twitter profil linklerini istediğimiz sayfada sadece kullanıcı adlarını yazmaları gerektiği açık değil.
```
  def twitter_url(user)
    "http://twitter.com/#{user.twitter}"
  end
```
Bazı kullanıcıların twitter linkleri
<img width="264" alt="Screen Shot 2020-06-22 at 22 55 42" src="https://user-images.githubusercontent.com/10260283/85330172-89725e00-b4dc-11ea-877d-71a2b5649717.png">
<img width="324" alt="Screen Shot 2020-06-22 at 22 55 51" src="https://user-images.githubusercontent.com/10260283/85330176-8aa38b00-b4dc-11ea-98e4-ac2759504a9d.png">
<img width="312" alt="Screen Shot 2020-06-22 at 22 55 58" src="https://user-images.githubusercontent.com/10260283/85330182-8b3c2180-b4dc-11ea-8d97-41a5ae59ebb9.png">
<img width="420" alt="Screen Shot 2020-06-22 at 22 56 19" src="https://user-images.githubusercontent.com/10260283/85330183-8bd4b800-b4dc-11ea-8a03-82d204f37642.png">

**Tekrarlamak için ne yapmalıyız?**
Tekrarlamak için yapılacaklar:
1. Hedef url adresine gidilir ```/users```
2. Genelikle son eklenen kullanıcıların twitter adreslerine bakılır. Ve bir çoğunun yanlış olduğu görülür.

**Olması gereken**
Formun şu şekilde olması kullanıcıları daha iyi bilgilendirecektir.

<img width="814" alt="Screen Shot 2020-06-22 at 23 08 51" src="https://user-images.githubusercontent.com/10260283/85330577-5da3a800-b4dd-11ea-889a-ad9912cf5d7c.png">

**Ek açıklamalar**
Ayrıca var olan tüm kullanıcı twitter linklerinde gezecek ve eğer içinde '/' var ise buna göre split edip son elemanı kullanıcı twitter linki olarak tekrar kaydedecek bir migration scripti yazılmalı.

**Comment by MuhammetDilmac** [comment]
Ayrıca bu durumun tekrar yaşanmaması için bir validation'da model'e yazılması çok hoş olur :)
