### ISSUE TITLE
[HATA] - Google groupların embedded olarak desteklenmemesi

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#162]
### Hatanın tarifi
Google grubu sayfası embeded olduğu için ve artik Google bunu desteklemediği için hata mesajı çıkıyor.

**Tekrarlamak için ne yapmalıyız?**
Tekrarlamak için yapılacaklar:
https://rubyturkiye.org/group sayfasına gidiniz.

**Olması gereken**
Belki sayfa hiç olmamalı bilmiyorum.
![Screen Shot 2021-04-17 at 18 54 40](https://user-images.githubusercontent.com/447588/115118951-9eaa0300-9fae-11eb-98e8-d82e9a40e606.png)

**Comment by MuhammetDilmac** [comment]
Baktımda gördüğüm kadarıyla bir alternatif yolu yok. Aslında rails action mailbox için güzel bir kullanım olur fakat heroku bu durumda pek iyi olmaz 🙂

**Comment by MuhammetDilmac** [comment]
Gördüğüm kadarıyla Google'ın buna bir çözümü yok. Aslında bu konu action mailbox için süper uygulama olur ama heroku'da sıkıntı olur :)

**Comment by ogirginc** [comment]
https://github.com/rubytr/ruby-tr/pull/184 buna ne dersiniz?

**Comment by enderahmetyurt** [comment]
Fixed: https://github.com/rubytr/ruby-tr/pull/184
