### ISSUE TITLE
[HATA] - (GitHub ile giriş sorunu)

### ISSUE THREAD

**Issue by idnzozkan** [rubytr/ruby-tr#167]
### Hatanın tarifi
GitHub ile giriş yapmak istendiğinde işlem devam etmiyor; yeni kayıt yapılamıyor.
URL: `https://rubyturkiye.org/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=fbbf3637321315898e01d59efde7f07a4f8b50982ade189c`

**Ekran görüntüleri**
![image](https://user-images.githubusercontent.com/59365742/120943913-69ae6700-c73a-11eb-87f0-5f7e0a98a3a1.png)

**Comment by kiliczsh** [comment]
@enderahmetyurt @MuhammetDilmac

**Comment by yasincad** [comment]
Simdi denedigimde de calismiyordu. 
Github'in Authorize ekrani geliyor, fakat sonra uygulamaya geri dondurunce su hatayi aliyorum:

![image](https://user-images.githubusercontent.com/65595348/143069103-0b86f303-b589-441a-8ffa-33ffd29dfae2.png)

URL: https://rubyturkiye.org/users/auth/github/callback?code=......state=......
