### ISSUE TITLE
[HATA] - (Error 525 – SSL handshake failed)

### ISSUE THREAD

**Issue by ogirginc** [rubytr/ruby-tr#174]
### Hatanın tarifi
https://www.rubyturkiye.org/ adresine gitmeye çalışıldığında SSL handshake hatası alınıyor.

**Tekrarlamak için ne yapmalıyız?**
Tarayıcında https://www.rubyturkiye.org/ adresine gitmek yeterli.

**Olması gereken**
Tıpkı https://rubyturkiye.org gibi hatasız bir şekilde siteye erişebilmeliyiz.

**Ekran görüntüleri**

<img width="1552" alt="Screenshot 2021-11-04 at 12 56 54" src="https://user-images.githubusercontent.com/7466873/140294033-7cdc72b4-615b-4e29-ac44-c8c95c9bab2d.png">

**Ek açıklamalar**
Konuyu fark edip Slack'te paylaşan kişi [Özgün](https://rubytr.slack.com/archives/C04DW01AZ/p1635878963014000). Ben sadece issue'sunu açtım.

**Comment by ozgun** [comment]
@paracycle bu sorunu giderdi, kapatıyorum bu issue'yu.

**Comment by ogirginc** [comment]
<img width="1199" alt="Screenshot 2022-06-06 at 13 18 16" src="https://user-images.githubusercontent.com/7466873/172142511-706ede6f-d69c-450c-b75c-5e66220bc3c1.png">
