### ISSUE TITLE
Topluluk sayfasındaki kişi sayısı

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#187]
![Screen Shot 2022-06-10 at 21 20 12](https://user-images.githubusercontent.com/447588/173127209-9d115e75-1676-4faa-a89d-e23cdb292ab0.png)

Bu sayfada pagination olduğu ve her sayfada 25 kayıt geldiği için toplam üye sayısı yazmıyor. Burada üye sayısı yazsa daha iyi olur diye düşünüyorum.

**Comment by mustafasakalli** [comment]
Merhabalar.  Projeyi ayağa kaldırmak için Windows 10'da WSL 2 (Ubuntu 18.04) ile sırasıyla aşağıdaki adımları takip ettim:
1) **rbenv kurulumu**
2) **ruby kurulumu (2.7.5 sürümü)**    `rbenv install 2.7.6`
3) `gem install bundler` 
4) `gem install rails -v 6.1.3`

`bundle install` yaptığımda PostgreSQL yüklü olmadığı için pg gem'i hata vermişti. PostgreSQL'i `sudo apt-get install postgresql postgresql-contrib libpq-dev` diyerek indirdikten sonra tekrar `bundle install` yaptım ve tüm gem'ler yüklendi.

Proje ayağa kalktığında ise `localhost:3000/users`  ve anasayfa düzgün görüntülenmediğini gördüm [burada](https://imgur.com/a/8MtCe6O) ekran görüntüsü mevcut

**Comment by yasarcelep** [comment]
@mustafasakalli Selam, Users section'ı içinde user olmadığı için öyle gözüküyor gibi. Eğer istersen Faker ve seeds'i kullanarak orada gözükecek çeşitli user'lar oluşturabilirsin.
Anasayfayı'da paylaştığın bağlantıda göremedim.

**Comment by enderahmetyurt** [comment]
@mustafasakalli @yasarcelep haklı. DB'de User yok. dediği gibi User ekleyebilirsin mock bir şekilde.
