### ISSUE TITLE
Anasayfaya sponsorları eklemek

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#203]
Mikrogroup Paraşüt ve Lab2023 sponsorumuz. Onların logolarını siteye koyabiliriz ve sponsor olmak isteyenler için bir iletişim bilgisi bırakabiliriz bu bir sayfa da olabilir. Belki bu şekilde olabilir.

![image](https://user-images.githubusercontent.com/447588/203863538-b25c2cc0-a28f-45a4-a766-56a628f56347.png)

**Comment by yasarcelep** [comment]
Selam, 
Güzel fikir. Şirketler genelde sıralı bir şekilde görünmek isterler mi, emin değilim. Yatay bir hiyerarşiyi, ne sponsoru olduklarını belki göstermek isteyebilirler.

**Comment by enderahmetyurt** [comment]
Sağol. Bu şekilde olsun demiyorum. sadece örnek.

**Comment by enderahmetyurt** [comment]
siteyi baştan yapalım

**Comment by tayfunoziserikan** [comment]
Katılıyorum.

**Comment by enderahmetyurt** [comment]
`index.php` yapıştırıp geçelim
