### ISSUE TITLE
Topluluk nüfusu

### ISSUE THREAD

**Issue by turhn** [rubytr/ruby-tr#37]
Merhaba,

http://www.rubyturkiye.org/people sayfasında 

#### Topluluk
olan başlık
#### Topluluk (136)
şeklinde gösterilse veya toplulukta kaç kişi olduğu daha yaratıcı bir şekilde sayfa ziyaretçilerine gösterilse daha iyi olmaz mı?

Hatta basit bir JS chart ile aylara göre topluluk sayısındaki değişimler de gösterilebilir.

**Comment by alienaut** [comment]
Merhabalar,

https://github.com/rubytr/ruby-tr/pull/38 'da isteğin özelllik ve biraz değişiklik var. Nasıl bir JS chart eklenir bilemiyorum, doğrusu. Bir örnek gösterebilir misin?
