### ISSUE TITLE
İş ilanları sekmesi

### ISSUE THREAD

**Issue by sdogruyol** [rubytr/ruby-tr#39]
Mail listesine son zamanlarda hatrı sayılacak sayıda iş ilanı geliyor bunu ana sayfada bir sekme haline getirebiliriz.

Örnek olarak: http://pyistanbul.org/jobs/

**Comment by alienaut** [comment]
Kötü içeriği engellemek için gelen ilanların yayınlanmadan önce basic authentication ile erişilebilen bir sayfada onaylanması gerektiren bir yapı düşündüm bunun. 

İyi mi sizce?

**Comment by Sdogruyol** [comment]
Olabilir.

Aslında activeadmin kullanabiliriz bu tarz resourceları yönetmek için.

**Comment by okanvurdu** [comment]
Selamlar abi,
Gezinirken gördüm; bir deneyeyim dedim. :smiley: 
Sonuçlar şurada:
https://github.com/rubytr/ruby-tr/pull/42

Yeterince dikkat ettim ama, umarım gözden kaçan bir nokta olamamıştır.

**Comment by dnomak** [comment]
:clap:

**Comment by enderahmetyurt** [comment]
@okanvurdu eline sağlık abi. böyle bir şeye cidden ihtiyacımız var. bakalım merge edelim PR'ını.

**Comment by okanvurdu** [comment]
@enderahmetyurt teşekkürler abi, topluluğa küçük de olsa bir faydamız dokunduysa ne mutlu... :blush:

**Comment by alienaut** [comment]
Bu neden yayından kaldırıldı?

**Comment by enderahmetyurt** [comment]
@alienaut ne yazık ki kaldırmak zorunda kaldık. Yasal değilmiş. Başıma dert açılabilirdi. Konu ile alakalı RubyTürkiye mail grubunda konu var. İnceleyebilirsin.
