### ISSUE TITLE
http / s prefix olmadan sitenin yanlış yere yönlenmesi

### ISSUE THREAD

**Issue by Sdogruyol** [rubytr/ruby-tr#40]
1 sene oldu hala bunu düzeltemedik ve LYK kampında öğrenciler siteye girmeye çalıştığında hepsi google mail grubuna gitmişti :( 

//cc @all @tayfunoziserikan @onurozgurozkan

**Comment by dnomak** [comment]
:+1:

**Comment by onurozgurozkan** [comment]
Domain anında transfer edilir. :)

Onur Özgür Özkan

**Comment by Sdogruyol** [comment]
@onurozgurozkan abi o zaman halledelim hayde :)

**Comment by enderahmetyurt** [comment]
Hangi 1 sene la :')

On Wed, Aug 12, 2015 at 10:59 PM, Serdar Dogruyol <notifications@github.com>
wrote:

> @onurozgurozkan <https://github.com/onurozgurozkan> abi o zaman
> halledelim hayde :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubytr/ruby-tr/issues/40#issuecomment-130427202>.
>



-- 
*Ender Ahmet Yurt*
Computer Engineer & Web Application Developer
*www.enderahmetyurt.com <http://www.enderahmetyurt.com>*

**Comment by tayfunoziserikan** [comment]
İşlem tamamdır :)

```http://rubyturkiye.org --> http://www.rubyturkiye.org```

Test edebilir misiniz dostlar?

**Comment by Sdogruyol** [comment]
Olmuş gibi gözüküyor Tayfun :+1:

**Comment by tayfunoziserikan** [comment]
:+1: Mis mis :)

**Comment by Sdogruyol** [comment]
Eline sağlık @tayfunoziserikan :clap:

**Comment by tayfunoziserikan** [comment]
Teşekkürler @Sdogruyol

**Comment by enderahmetyurt** [comment]
eyvallah @tayfunoziserikan <https://github.com/tayfunoziserikan>

On Thu, Aug 13, 2015 at 9:44 AM, Serdar Dogruyol <notifications@github.com>
wrote:

> Eline sağlık @tayfunoziserikan <https://github.com/tayfunoziserikan> [image:
> :clap:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubytr/ruby-tr/issues/40#issuecomment-130556378>.
>



-- 
*Ender Ahmet Yurt*
Computer Engineer & Web Application Developer
*www.enderahmetyurt.com <http://www.enderahmetyurt.com>*
