### ISSUE TITLE
Üye hesap ekranı

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#45]
Üyelerin kendi bilgilerini günceleyebildiği bir ekran.

**Comment by yigitozkavci** [comment]
Bunun için authentication'a ihtiyaç var, GitHub login'i nasıl olur? omniauth-github ile email-password ile insanları yormadan profillerini düzenletebiliriz sanki

**Comment by enderahmetyurt** [comment]
PR'larını bekliyoruz 🖌

**Comment by yigitozkavci** [comment]
Tamamdır 👍

**Comment by enderahmetyurt** [comment]
Closed #45
