### ISSUE TITLE
Twitter ve Github bilgisi olmayan insanların altındaki icon'lar yanlış adrese yönleniyor

### ISSUE THREAD

**Issue by yigitozkavci** [rubytr/ruby-tr#46]
Eğer kişinin Twitter'ı yoksa `https://twitter.com`, Github'ı yoksa `https://github.com`a yönleniyor.

Beklenen davranış:
Olmayan sosyal medya hesapları için ikon gözükmemesi. Halihazırda ikonlar centered oldukları için front-end'de problem yaratmayacak

**Comment by enderahmetyurt** [comment]
Closed #47
