### ISSUE TITLE
Üye profil fotoğraflarının değiştirilmesi

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#55]
Merhaba,

Github ile giriş yapılabiliyor artık RubyTR'ye. Eskiden Gravatar'dan çekiyorduk üye profil fotograflarını. Yeni sistemde Github ile giriş dışında bir giriş ve kayıt olmadığı için Github profil resmi ile bunu değiştirelim diyoruz. Böylelikle email değiştirince profile resmi de değişmeyecek.

Ne dersiniz bu konuda? Henüz Github ile giriş yapmayanların profil resimleri Gravatar kalabilir.

Sevgiler.

**Comment by sdogruyol** [comment]
Bence gayet mantıklı 👍

**Comment by enderahmetyurt** [comment]
Closed by #54
