### ISSUE TITLE
Kaynaklar

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#58]
Türkçe ya da İngilizce kitap, video vb kaynaklara ulaşabilecekler listesi.

**Comment by ekremkaraca** [comment]
@enderahmetyurt Kaynak derken Ruby veya Rails ile ilgili yazılı/görsel içerikler, bloglar, vb. ekleyebiliriz sanırım. Reddit'in Ruby ile Rails sayfalarından araklama yapabiliriz.

**Comment by enderahmetyurt** [comment]
Araklama yapma gerek yok. Biraz burası insanlar kaynak nereden edinebilirim vs sorularına cevap bulabilsin diye düşünmüştüm. Bir de kendi blog'larında yazdıkları ve rubytr'de göstermek istediği postları olursa insanların onların link'lerine de koyabiliriz diye düşünüyorum.

**Comment by enderahmetyurt** [comment]
@ekremkaraca bu konuyu ne yaptın? #59 vardı kapamışsın

**Comment by MuhammetDilmac** [comment]
Bence ilk olarak bu issue altında kaynakları toplayalım, ardından sitede yeni bir sekme yapar oraya ekleriz @enderahmetyurt

**Comment by enderahmetyurt** [comment]
Aslında kaynakları bir readme gibi yapsak ayrı repoda o da güzel olabilir. Sonra siteye alırız content oluşunca.

**Comment by ekremkaraca** [comment]
Mantıklı, hatta şu adreste oluşturmaya başladım bile: https://github.com/ekremkaraca/ruby-kaynaklar

**Comment by enderahmetyurt** [comment]
Bu konu için https://github.com/rubytr/ruby-kaynaklar şeklinde bir repo açtık. Verileri biraz orada toplayıp, siteye taşıyabiliriz.
