### ISSUE TITLE
Şirketlerin alfabetik sıralanması

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#63]
Merhaba,

Şirketlerin alfabetik sıralanması daha hoş olacaktır diye düşünüyorum. 🤓

**Comment by msdundar** [comment]
Kesinlikle :+1: 

Datatables (https://datatables.net/) gibi bir şey eklemeye ne dersiniz?

**Comment by enderahmetyurt** [comment]
Bence şuan gerek yok. Direk isme göre sıralasın A-Z şeklinde yeterli.
