### ISSUE TITLE
Şirket Eklenince Admin'e Notification Gitmesi

### ISSUE THREAD

**Issue by msdundar** [rubytr/ruby-tr#64]
Birisi şirketini dizine ekleyince adminin haberdar olabilmesi ve review yapabilmesi için notification maili gönderilebilir.

**Comment by enderahmetyurt** [comment]
Evet şirket, kişi vb şeyler için mail gelebilir admin'lere.

**Comment by ekremkaraca** [comment]
Şöyle birşey kullanabiliriz: https://github.com/simukappu/activity_notification

**Comment by yigitozkavci** [comment]
Slack +1

**Comment by msdundar** [comment]
Slack mantıklı +1

**Comment by enderahmetyurt** [comment]
Slack okey de admin olan zaten 2-3 kişi zaten fazlası da olmasına gerek yok diye düşünüyorum.
