### ISSUE TITLE
Sosyal medya hesapları

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#67]
Ruby Türkiye için Twitter, Facebook ve Meetup hesaplarını eklemek gerekiyor.

**Comment by MuhammetDilmac** [comment]
Üst tarafta twitter ve slack var sanırım hepsini toplu olarak footer'da sağ tarafa almamız hoş olacaktır. Eğer okey ise merge atayım

**Comment by enderahmetyurt** [comment]
@MuhammetDilmac sen bi çalışma yap abi. Buraya koy bakalım . Çoğunluk beğenirse merge ederiz.
