### ISSUE TITLE
Yakut'u siteye eklesek mi?

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#68]
Ne dersiniz? Yakut'u sağ frame'de alt tarafa koyalım mı? Son bölümleri dinle gibi bişiler. Ne dersiniz?

**Comment by sdogruyol** [comment]
Çok güzel fikir :+1:

**Comment by puskuruk** [comment]
Çok şık durur fakat autoplay yapmayalım. (Y)

**Comment by MuhammetDilmac** [comment]
Güzel fikir bence eklenmeli 👍

**Comment by sdogruyol** [comment]
Neden hala eklemedik :thinking:

**Comment by MuhammetDilmac** [comment]
Sonuçlanmasını bekliyorum eğer okeylenirse ekleyeceğim ben akşam :)

**Comment by MuhammetDilmac** [comment]
@sdogruyol Sonuçlanmasını bekliyorum eğer okeylenirse ekleyeceğim ben akşam :)

**Comment by enderahmetyurt** [comment]
Burada UI önemli. Başka branch'lerde çalışıp, PR gönderebilirsiniz.

**Comment by muratbsts** [comment]
@enderahmetyurt ben codepen de zamanında şöyle bir çalışma yapmıştım. https://codepen.io/muratbastas/pen/rOXEMm

Şimdi podcast için uygun olacağını düşündüğüm şöyle bir player yazmaya çalışıyordum fakat yeterli zaman bulamayıp tamamlayamadım. 

https://codepen.io/muratbastas/pen/zEPWKo

Eğer alıp devam ettirecek birisi varsa beğenen buyursun. Kimse yapmazsa ben vakit ayırabildiğim zaman yapacağım.

**Comment by enderahmetyurt** [comment]
@muratbsts çalışmaların çok güzel. Eline sağlık. @MuhammetDilmac bu konuya çalışmış, daha minimal bir iş çıkarmış. Burada paylaşır mısın @MuhammetDilmac screenshot'ı?

**Comment by MuhammetDilmac** [comment]
Tabi şöyle bir şey hazırlamıştım

![Yakut](https://i.imgur.com/3NqKe6X.png "Image")

**Comment by enderahmetyurt** [comment]
bence güzel iş görür. Ne dersiniz?

**Comment by enderahmetyurt** [comment]
Yakut'u artık yapamıyoruz. Gün gelir Yakut ya da bu konuda başka bir podcast olur o zaman tekrar gündeme alırız bu konuyu.
