### ISSUE TITLE
Post modeli

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#70]
Merhaba,

Anasayfadaki yazılar statik bir şekilde ekleniyor. Bunları bir Post modeli tanımlayıp, active admin'den admin yetkisi olanlar yazabilse. İlerleyen vakitlerde meetup vs konularda yazılar yazmak gerekebilir. Böyle bir alt yapı nasıl olur?

Sevgiler.

**Comment by sdogruyol** [comment]
Gayet iyi olur :+1:
