### ISSUE TITLE
Markdown desteği

### ISSUE THREAD

**Issue by ekremkaraca** [rubytr/ruby-tr#72]
<s># 70</s> #71'de de değinildiği üzere; duyuruları eklerken düz metin yerine Markdown destekli editör kullanılması daha iyi olur.

**Comment by enderahmetyurt** [comment]
Editöre gerek yok bence. Ekrana basılırken markdown olduğunu anlayıp bassın yeter.

**Comment by enderahmetyurt** [comment]
https://github.com/vmg/redcarpet gibi birşey. ben "# bu bir h1" o markdown'a cevirecek. zor olacaksa editör falan karıştırmaya gerek yok.

**Comment by ekremkaraca** [comment]
o zaman kramdown ya da redcarpet ile render etmek yerinde olacaktır.

**Comment by ekremkaraca** [comment]
Markdown render etme olayı tamamdır, son commit'le onu da hallettim. Geriye testler kalıyor.

**Comment by MuhammetDilmac** [comment]
İstek geldiği anda render etmek yerine kayıt veya update anında html'e çevirmek daha iyi olabilir mi?

**Comment by enderahmetyurt** [comment]
View içinde render etmeyelim model de mi edelim diyorsun?

**Comment by MuhammetDilmac** [comment]
Evet abi o şekilde söylüyorum @enderahmetyurt

**Comment by enderahmetyurt** [comment]
@MuhammetDilmac  peki before_save'den önce cevirip html olarak mı DB'de saklıcaz

**Comment by MuhammetDilmac** [comment]
Bence daha iyi olacaktır diye düşünüyorum abi @enderahmetyurt
