### ISSUE TITLE
Sign out unexpected error

### ISSUE THREAD

**Issue by sdogruyol** [rubytr/ruby-tr#73]
Currently sign out fails with an unexpected 500 error.

Here's an attached screenshot
![screenshot from 2017-09-22 21-17-22](https://user-images.githubusercontent.com/990485/30758557-8f3d86e8-9fdb-11e7-8bae-cfb87e21d96b.png)

**Comment by enderahmetyurt** [comment]
Evet bana da oldu. @yigitozkavci bakabilir misin?

**Comment by yigitozkavci** [comment]
Tamamdır bakacağım

**Comment by enderahmetyurt** [comment]
özel bir şirkette çalışsak bu kadar hızlı reaksiyon alamazdık. Enerjiye bakar mısın 😄

**Comment by sdogruyol** [comment]
Sinerji :heart:

**Comment by enderahmetyurt** [comment]
Fixed #74
