### ISSUE TITLE
Github authentication ile şirket eklenmesi

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#77]
Herkes kafasına göre şirket ekleyebiliyor. Bence Github ile giriş yapmamış kimse şirket ekleyemesin. Ekleyen kişinin de Github account'u görünsün. Çok saçma şirketler ekleniyor çünkü son zamanlarda. Kimin ne eklediği belli değil.

Ne dersiniz?

**Comment by yigitozkavci** [comment]
Katılıyorum. Admin ekleyen kişinin github hesabına girip gerçekliğini de kontrol edebilir

**Comment by enderahmetyurt** [comment]
Tamam o da olur da. Benim demek istediğim Github ile People tablosuna kayıt olmamış biri Company ekleyemesin. O kontrol de ayrı gözle yapılabilir. Gerçi birçok Github profili boş 🙄

**Comment by enderahmetyurt** [comment]
resolved #78
