### ISSUE TITLE
Username div problemi

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#79]
Merhaba Github ile giriş yapınca benim gibi ismi soy ismi uzun olanlar için sorun çıkıyor sanırım.
![screen shot 2017-09-29 at 12 20 39](https://user-images.githubusercontent.com/447588/31009605-bd1a4a94-a510-11e7-8433-df2dc173145f.png)

**Comment by muratbsts** [comment]
Kullanılan grid'e sığmıyor isim. Buton genişlese bile o satıra sığamaz. İsmi alttaki gibi ellipsis ile truncate edebiliriz. Uygun olur mu?

![image](https://user-images.githubusercontent.com/1137480/31014012-72153df4-a521-11e7-8345-add52c1a612d.png)

**Comment by enderahmetyurt** [comment]
Aynen. 👍

**Comment by ekremkaraca** [comment]
Dış bağlantılar ya da kullanıcı yönetim kısmı için bir dropdown yapılabilir.

**Comment by enderahmetyurt** [comment]
@ekremkaraca şu vadede böyle birşeye gerek yok bence. İleride olabilir.
