### ISSUE TITLE
Meetup Entegrasyonu

### ISSUE THREAD

**Issue by MuhammetDilmac** [rubytr/ruby-tr#85]
Bence yaklaşan meetup'ları sayfada sağ tarafta menüde gösterebiliriz?

**Comment by ekremkaraca** [comment]
Meetup.com'da tanımladığımız meetup detaylarını mı siteye çekelim yoksa yeni bir meetup/event resource'u oluşturup oradan mı yürüyelim? Daha da açmak adına soruyorum.

**Comment by MuhammetDilmac** [comment]
API'ye baktığımda her hangi bir token'a gerek yok bence meetup'da açılan event'ın adını, tarihini ve yerini alıp sayfada sağda menüde göstermek yeterli olacaktır. Bunun içinde bence js ile yapabiliriz ruby'e karıştırmadan

**Comment by muratbsts** [comment]
Eğer bunu yapan kimse yok ise ben sağ sidebar'da en tepeye yerleştirebilirim?

```
curl -X GET "https://api.meetup.com/Ruby-Turkiye/events"
```

**Comment by enderahmetyurt** [comment]
@muratbsts kendine assign edip yapar mısın bi çalışma? Tepede mi olur bilemedim açıkcası.

**Comment by muratbsts** [comment]
@enderahmetyurt tepede dememin sebebi zaten yeni event yok ise görünmeyecek olması. Var ise tepede görünmesi iyi olabilir diye düşündüm. Şuan bu endpoint den bir event gelmeyecek, bir önceki eventi göstererek ekran görüntüsü alıp gönderir, yaklaşan eventi gösterir şekilde bırakıp PR açarım.

**Comment by muratbsts** [comment]
#91 ile bir seyler yaptım.
