### ISSUE TITLE
Türkçe Projeler

### ISSUE THREAD

**Issue by MuhammetDilmac** [rubytr/ruby-tr#86]
Burada ki projeyi bence siteye ekleyebiliriz. Aynı firmalar gibi bir işleyiş ile herkes projesini ekler ve bilgilerini api ile çekip gösterebiliriz diye düşünüyorum. Eğer uygun görülür ise yapayım 👍  https://github.com/rubytr/projects

**Comment by enderahmetyurt** [comment]
Projeler bi toplaşsın o da olacak.
