### ISSUE TITLE
Github callback problem

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#87]
Yeni kullanıcı girişinde ya da kullanıcı girişince Github callback'ınde sıkıntı var. Aslında herşey normal görünüyor Github ayarlarında ama kodlar da bi değişiklik yapılmış olabilir.

**Comment by yigitozkavci** [comment]
Localhost'tan mı deneniyor bu mevzubahis Github login? Callback url'si production için geçerli çünkü, eğer development ortamında test etmek isteniyorsa Github'dan bir oauth application'u açıp `config/initializers/devise.rb` dosyasında o değerleri girerek test edilebilir. Şu anda rubyturkiye.org'da böyle bir sorun yok

**Comment by enderahmetyurt** [comment]
@MuhammetDilmac hatayı nasıl aldığını anlatır mısın?

**Comment by MuhammetDilmac** [comment]
Selamlar, dün sorunu yaşarken bugün sitede sorun yaşamadım. Benim browserdan kaynaklı olabilir sanırım.
