### ISSUE TITLE
Navigation problemi

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#88]
Loggedin bir user varken navigationda bozukluk var.
![screen shot 2017-10-09 at 16 54 37](https://user-images.githubusercontent.com/447588/31341579-9bbefa66-ad12-11e7-9f13-6ed298807bfe.png)

**Comment by MuhammetDilmac** [comment]
İlgileniyorum akşam PR gelmiş olur @enderahmetyurt
