### ISSUE TITLE
Oyunlaştırma

### ISSUE THREAD

**Issue by enderahmetyurt** [rubytr/ruby-tr#95]
Merhaba,

Garip bir fikir olabilir ancak belki Türkiye'de Ruby ile en azından open source olarak kod yazımını arttırmak adına altta bahsedeceğim gibi bir feature geliştirebiliriz diye düşünüyorum.

rubytukiye.org'a hepimiz Github ile login olduğumuz için açık repo'larımıza API erişebiliyor. Buradan bir kural seti oluşturup, kişileri puanlayabilir ve bir ranking yapabiliriz. Atıyorum user'ın Ruby ile yazmış olduğunu open source bir projesi var +10 puan ve her star başına +1 puan gibi. İşte takipci başına 0.5 puan vs gibi şeyler. Henüz detaylı düşünmedim.

Ne dersiniz?

**Comment by muratbsts** [comment]
Bence hoş bir fikir, open source bir şeyler üretmek için bahane motivasyon sağlayabilir.

**Comment by murat** [comment]
2018 den kalma bir mevzu imis, ben de cevap vermisim yeniden çıktı karşıma, bunun üzerinde çalışmaya başlasam mı?

**Comment by MuhammetDilmac** [comment]
Github da ki repoların üzerine gitmek pek doğru olmaz da rubytr'ye ekleyeceğimiz modüller üzerinde bunu yapmak bence daha iyi olur

**Comment by murat** [comment]
Ne gibi modüller abi, fikir verebilir misin? Ya da bunu bir ara düşünüp tasarlasak mı? Github repolarını da belirli aralıklarla kontrol etmek yerine belki kullanıcının profiline girdiğinde güncelleme emri vermesi gibi tetikleyebiliriz diye düşünmüştüm.

**Comment by MuhammetDilmac** [comment]
Benim aklımda Q&A ve Blog konuları var eğer notion'da var isen oraya yazdım :) Seninde aklında bir şeyler varsa onlarıda yazabilirsin oraya :)
